### ISSUE TITLE
Instances-at-Glance dashboard duplicate User Connections values  on ALL dashboards.

### ISSUE THREAD

**Issue by sliwa95** [tboggiano/grafana#2]
Hello,

Noticed this after adding our biggest and busiest instance. User Instance values for every monitored instance on Activity Panel, displays maximum valuse from all monitored instances.
![grafana_issue](https://user-images.githubusercontent.com/16031593/46599958-f5cee300-cae8-11e8-80f9-4f953b62d2a9.jpg)

**Comment by sliwa95** [comment]
I have implemented modification to template You have suggested on Slack channel. Now it looks like it is using minimum value for all monitored instances (or some kind of aggregate?)

On this screenshot Helpdesk instance shows value 0.03
![grafana-2-instance-at-glance](https://user-images.githubusercontent.com/16031593/46601529-a6d77c80-caed-11e8-9ddb-0924a891b72d.jpg)

While Instance Overview for same Helpdesk instance displays value 21
![grafana-2-instance-overview](https://user-images.githubusercontent.com/16031593/46601530-a6d77c80-caed-11e8-8050-e78ff7812e1a.jpg)

**Comment by tboggiano** [comment]
I've committed a new dashboard that fixed this issue.
