### ISSUE TITLE
Windows server Stats Dashboard - nothing displayed

### ISSUE THREAD

**Issue by eliassal** [tboggiano/grafana#3]
Tracy, wonderful and  very useful stuff, good job. I followed your instructions and getting nice dasboards for sql except that "Windows server Stats Dashboard" is always empty, any idea of what is going wrong?
Thanks

**Comment by tboggiano** [comment]
Just guessing that you looking for Windows stats for you SQL Servers?  If so please add the INPUT PLUGINS portion from the Windows Conf (https://github.com/tboggiano/grafana/blob/master/ConfigFiles/telegraf_windows.conf) to the SQL conf file you installed on your system and restart the service.  If you are strictly trying to monitor only windows, try running Telegraf at the command prompt and see if it post any errors and post those back here.

**Comment by tboggiano** [comment]
Any update on rather you were able to resolve your issue?

**Comment by tboggiano** [comment]
No response back so going to assume issue was resolved.
