### ISSUE TITLE
tried all but 1 working

### ISSUE THREAD

**Issue by ousturali** [tboggiano/grafana#4]
first of all thanks a lot for the efforts , you did a great job 
ı followed your direcitons, and i can monitor lots of staff with influx and grafana,but when it comes to sql 
there are issues, 
ı imported your dashboards by copy and paste the JSON file ,and got the following error
"Templating init failed Datasource named was not found"

Do you have any idea regarding it?
regards

**Comment by tboggiano** [comment]
Check that your datasource name matches the pattern of the variable Influxdb-XX or just name is the same as the direction if you didn't InfluxDB-01.  If that is not the issue put a print screen of the datasource you are using in the issue.  Or email to me.  My email is my website.

**Comment by ousturali** [comment]
Hi again tboggiano,
i followed your advice, and changed the influxdb-XX with my datasource name ,and they started to work 
much regards and thanks 
and also for the fast responce back ,i appriciate much
