### ISSUE TITLE
Instance Overview.json error message when importing

### ISSUE THREAD

**Issue by nmacehiter** [tboggiano/grafana#5]
When I import the Instance Overview.json I receive the following message:

Templating init failed
Datasource named was not found.

I can enter InfluxDB at the top left of the Dashboard and it functions correctly but it does not save the variable setting so I have to repeat this each time I open the Dashboard

**Comment by tboggiano** [comment]
The template really looks for the name of the data source to be InfluxDB-01, so I would rename to that if isn't named that and see if that fixes your issue.

**Comment by nmacehiter** [comment]
Thanks for the response. I actually resolved it by changing the definition of the Datasource variable to remove the Instance name filter and it then showed InfluxDB in the preview of values
